[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
betting = "BRjpCHtyQLf1gWwUPQPqsqZbBsmXtmvUNVEi7t9kfPLe"
token_granting = "H4LdKdwJE1B2qGURGWotvo3oaS14Dj63GsUk5eXuioaq"

[programs.testnet]
betting = "BRjpCHtyQLf1gWwUPQPqsqZbBsmXtmvUNVEi7t9kfPLe"
token_granting = "H4LdKdwJE1B2qGURGWotvo3oaS14Dj63GsUk5eXuioaq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "NODE_OPTIONS='--max-old-space-size=512' yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
